server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ewm}
    username: ${SPRING_DATASOURCE_USERNAME:ewm}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: false

logging:
  level:
    ru.practicum: DEBUG
    ru.practicum.main.controller: DEBUG
    ru.practicum.main.service: DEBUG
    org.springframework.web: DEBUG
stats-server:
  url: ${STATS_SERVER_URL:http://localhost:9090}